name: ecopamoja
description: "An app designed to bring together environment enthusiasts and build a greener future."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8 # for iOS style icons
  shared_preferences: ^2.5.3 #check whether user has completed onboarding
  google_fonts: ^6.2.1 # for custom fonts
  iconsax: ^0.0.8 # for icons
  flutter_riverpod: ^2.6.1 # for state management
  riverpod_annotation: ^2.6.1 # for code generation
  go_router: ^16.0.0 # for routing
  firebase_core: ^4.0.0 # for Firebase integration
  firebase_auth: ^6.0.0 # for user authentication
  google_sign_in: ^6.1.4 # for Google Sign-In
  responsive_framework: ^1.5.1 # for responsive design
  lottie: ^3.3.1 # for Lottie animations
  flutter_secure_storage: ^9.2.4 #for storing user data
  cloud_firestore: ^6.0.0 # for Firestore database
  intl: ^0.20.2 # for internationalization
  firebase_storage: ^13.0.0 # for storing images in Firebase
  file_picker: ^10.2.0 # for picking files
  http: ^1.4.0
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.5
  carousel_slider: ^5.1.1
  share_plus: ^11.0.0 
  flutter_native_splash: ^2.4.6
  google_nav_bar: ^5.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0 # for linting
  flutter_launcher_icons: ^0.14.3 # for app icons
  riverpod_generator: ^2.6.4 # for code generation
  test: ^1.25.15


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  web: true

  branding: assets/images/branding.png
  branding_mode: bottom
  branding_bottom_padding: 30

  android_12:
    color: "#000000"
    branding: assets/images/branding.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/

  