// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgkia7UbasFdw9Gkh8LKHImo_WjdZOvxg',
    appId: '1:912077992479:web:2b8cf07a6f2e58de435b2a',
    messagingSenderId: '912077992479',
    projectId: 'ecopamoja',
    authDomain: 'ecopamoja.firebaseapp.com',
    storageBucket: 'ecopamoja.firebasestorage.app',
    measurementId: 'G-MTVP07YZCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfCSTmc09z6F_yD0YMLODoFwN8ViyxgiM',
    appId: '1:912077992479:android:799dba8fa92aab41435b2a',
    messagingSenderId: '912077992479',
    projectId: 'ecopamoja',
    storageBucket: 'ecopamoja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSgiwnxYck2YhwQLe-k69mmEr0G0Jboc',
    appId: '1:912077992479:ios:507d8419d9362231435b2a',
    messagingSenderId: '912077992479',
    projectId: 'ecopamoja',
    storageBucket: 'ecopamoja.firebasestorage.app',
    iosClientId: '912077992479-14q7utpp6chtp13bgs92rh3qd1tl1f4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecopamoja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSgiwnxYck2YhwQLe-k69mmEr0G0Jboc',
    appId: '1:912077992479:ios:507d8419d9362231435b2a',
    messagingSenderId: '912077992479',
    projectId: 'ecopamoja',
    storageBucket: 'ecopamoja.firebasestorage.app',
    iosClientId: '912077992479-14q7utpp6chtp13bgs92rh3qd1tl1f4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecopamoja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgkia7UbasFdw9Gkh8LKHImo_WjdZOvxg',
    appId: '1:912077992479:web:8e6c2fee1f494d12435b2a',
    messagingSenderId: '912077992479',
    projectId: 'ecopamoja',
    authDomain: 'ecopamoja.firebaseapp.com',
    storageBucket: 'ecopamoja.firebasestorage.app',
    measurementId: 'G-0GFWM7W2YW',
  );
}
