import 'package:flutter/material.dart';

final List<Map<String, dynamic>> availableIcons = [
    {'name': 'Nature', 'icon': Icons.nature},
    {'name': 'Recycle', 'icon': Icons.recycling},
    {'name': 'Eco', 'icon': Icons.eco},
    {'name': 'Park', 'icon': Icons.park},
    {'name': 'Bike', 'icon': Icons.pedal_bike},
    {'name': 'Water', 'icon': Icons.water_drop},
    {'name': 'Energy', 'icon': Icons.bolt},
    {'name': 'Clean', 'icon': Icons.cleaning_services},
    {'name': 'Leaf', 'icon': Icons.spa},
    {'name': 'Tree', 'icon': Icons.forest},
    {'name': 'Lightbulb', 'icon': Icons.lightbulb},
    {'name': 'Compost', 'icon': Icons.compost},
    {'name': 'Air', 'icon': Icons.air},
    {'name': 'Garden', 'icon': Icons.yard},
    {'name': 'Electric Car', 'icon': Icons.electric_car},
    {'name': 'Solar Power', 'icon': Icons.solar_power},
    {'name': 'Wind Power', 'icon': Icons.wind_power},
    {'name': 'Fireplace', 'icon': Icons.fireplace},
    {'name': 'Trash', 'icon': Icons.delete_outline},
    {'name': 'Cloud', 'icon': Icons.cloud},
    {'name': 'Flower', 'icon': Icons.local_florist},
    {'name': 'Hand Wash', 'icon': Icons.soap},
    {'name': 'Plant', 'icon': Icons.grass},
    {'name': 'Globe', 'icon': Icons.public},
    {'name': 'Heart', 'icon': Icons.favorite},
    {'name': 'Shield', 'icon': Icons.shield},
    {'name': 'Star', 'icon': Icons.star},
    {'name': 'Check Circle', 'icon': Icons.check_circle},
    {'name': 'Warning', 'icon': Icons.warning},
  ];